name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - task-3-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Task 3 website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gokulpr-1@mulearn/Task-3
          publish_branch: gh-pages
          keep_files: false
